apiVersion: v1
kind: Namespace
metadata:
  name: dedicated
---
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
  namespace: dedicated
spec:
  template:
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "batch"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: dedicated
                    operator: In
                    values:
                      - batch
      containers:
      - name: busybox
        image: busybox
        env:
          - name: MAX_COUNT
            value: "30"
        command: ["/bin/sh", "-c"]
        args:
          - echo "[$(date +"%T")] Job started"; i=1; while [ $i -le $MAX_COUNT ]; do echo $i; i=$((i+1))
            ; sleep 1; done; echo "[$(date +"%T")] Job Done!";
      restartPolicy: OnFailure
